using Core.Interface;
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace Core.Entity
{
    /// <summary>
    /// 會員資產
    /// </summary>
    public partial class Asset : IBaseEntity
    {
        public Asset()
        {
            //ExecDetails = new HashSet<ExecDetail>();
            //AssetDetails = new HashSet<AssetDetail>();
        }

        public int Id { get; set; }
        public string SourceType { get; set; }
        public int? SourceId { get; set; }
        public int? UnitCount { get; set; }
        public DateTime? CreateTime { get; set; }
        public DateTime? UpdateTime { get; set; }

        public int ClinicProductId { get; set; }
        public int ClinicMemberId { get; set; }
        public int? InitUnitCount { get; set; }
        /// <summary>
        /// 資產剩餘價值
        /// </summary>
        public int? ResidualAmt { get; set; }
        public DateTime? ValidBegTime { get; set; }
        public DateTime? ValidEndTime { get; set; }
        public string Status { get; set; }
        public decimal? InitPrice { get; set; }
        public decimal? InitBonusExclude { get; set; }
        public string ProductType { get; set; }
        public int? OrderDetailId { get; set; }
        //public virtual ClinicMember ClinicMember { get; set; }
        //public virtual ClinicProduct ClinicProduct { get; set; }
        //public virtual ICollection<ExecDetail> ExecDetails { get; set; }
        //public virtual ICollection<AssetDetail> AssetDetails { get; set; }
    }
}

