// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

using Microsoft.EntityFrameworkCore;

namespace Core.Entity
{
    public partial class YogurtContext : DbContext
    {
        public YogurtContext()
        {
        }

        public YogurtContext(DbContextOptions<YogurtContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Asset> Asset { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.UseCollation("utf8mb4_0900_ai_ci")
                .HasCharSet("utf8mb4");

            modelBuilder.Entity<Asset>(entity =>
            {
                entity.HasIndex(e => e.ClinicMemberId, "FK_Reference_164");

                entity.HasIndex(e => e.ClinicProductId, "FK_Reference_165");

                entity.Property(e => e.Id).HasColumnType("int(11)");

                entity.Property(e => e.ClinicMemberId).HasColumnType("int(11)");

                entity.Property(e => e.ClinicProductId).HasColumnType("int(11)");

                entity.Property(e => e.UnitCount).HasColumnType("int(11)");

                entity.Property(e => e.CreateTime).HasMaxLength(6);

                entity.Property(e => e.InitUnitCount).HasColumnType("int(11)");

                entity.Property(e => e.ResidualAmt).HasComment("資產剩餘價值").HasColumnType("int(11)");

                entity.Property(e => e.SourceId).HasColumnType("int(11)");

                entity.Property(e => e.SourceType).HasMaxLength(50);

                entity.Property(e => e.UpdateTime).HasMaxLength(6);

                entity.Property(e => e.ValidBegTime).HasMaxLength(6);

                entity.Property(e => e.ValidEndTime).HasMaxLength(6);

                entity.Property(e => e.Status).HasMaxLength(3);

                entity.Property(e => e.InitPrice).HasPrecision(12, 3);

                entity.Property(e => e.InitBonusExclude).HasPrecision(12, 3);

                entity.Property(e => e.ProductType).HasMaxLength(2);

                entity.Property(e => e.OrderDetailId).HasColumnType("int(11)");

                //entity.HasOne(d => d.ClinicMember)
                //    .WithMany(p => p.Assets)
                //    .HasForeignKey(d => d.ClinicMemberId)
                //    .HasConstraintName("FK_Reference_164");

                //entity.HasOne(d => d.ClinicProduct)
                //    .WithMany(p => p.Assets)
                //    .HasForeignKey(d => d.ClinicProductId)
                //    .HasConstraintName("FK_Reference_165");
            });


            OnModelCreatingPartial(modelBuilder);

            //YogurtContextConfig.ApplyConfig(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);

    }
}

